[tools]
act = "latest"
erlang = "27"
just = "latest"
pnpm = "latest"
uv = "latest"
elixir = "1.18.1-otp-27"
node = "22"
vale = "latest"
shellcheck = "latest"
java = "openjdk-21"
lychee = "latest"
stripe = "latest"
gh = "latest"
ghq = "latest"
pre-commit = "latest"
caddy = "latest"
sqlite = "latest"

[settings]
idiomatic_version_file_enable_tools = []
